### ISSUE TITLE
File encoding error

### ISSUE THREAD

**Issue by initd1** [initd1/HackAlert#29]
**Describe the bug**

**To Reproduce**
1. On a Windows environment, run `python main.py`
2. The following error appears:
```python
Traceback (most recent call last):
  File "H:\Code\Cyber-Breach-Detector\main.py", line 14, in <module>
    from Common import utils
  File "H:\Code\Cyber-Breach-Detector\Common\utils.py", line 18, in <module>
    configure_logging()
  File "H:\Code\Cyber-Breach-Detector\Config\config.py", line 52, in configure_logging
    logging_config = get_logging_config()
  File "H:\Code\Cyber-Breach-Detector\Config\config.py", line 44, in get_logging_config
    config = get_config('Config/logger.ini')
  File "H:\Code\Cyber-Breach-Detector\Config\config.py", line 19, in get_config
    config.read(config_file_path)
  File "C:\Users\kash\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Users\kash\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 1020, in _read
    for lineno, line in enumerate(fp, start=1):
  File "C:\Users\kash\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 152: character maps to <undefined>
``` 

**Expected behavior**
The script must run without errors and output the results of detected breaches for IP, Email or Username.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - IDE: Visual Studio Code
 - Python Version: 3.9.13

**Comment by GH-Syn** [comment]
As its a UnicodeDecodeError I have a feeling its to do with the emojis I'll have a look.

**Comment by initd1** [comment]
> As its a UnicodeDecodeError I have a feeling its to do with the emojis. I can't run it on a windows env, but it might be good to use tox as a way to verify changes on multiple operating systems before anything is merged. This way its cross-compatible with all operating systems.

Good call. Could you share some info on how to best use tox from your experience? Probably something to be documented in [Repo Ideas](https://github.com/initd1/HackAlert/discussions/categories/ideas)

I was also thinking of packaging the code in a light weight Docker container like python-slim and run the code from it. That way, the environment is set and can be run from any environment that supports docker. 

Happy to consider all options.
